namespace Tool
{
    public static class CountriesDict
    {
        public static readonly Dictionary<string, string> NameToCode = new Dictionary<string, string>
        {
            { "Global", "Global" },
            { "Unknown", "Unknown" },
            { "Australia", "AU" },
            { "United States", "US" },
            { "Andorra", "AD" },
            { "United Arab Emirates", "AE" },
            { "Afghanistan", "AF" },
            { "Antigua and Barbuda", "AG" },
            { "Anguilla", "AI" },
            { "Albania", "AL" },
            { "Armenia", "AM" },
            { "Netherlands Antilles", "AN" },
            { "Angola", "AO" },
            { "Antarctica", "AQ" },
            { "Argentina", "AR" },
            { "American Samoa", "AS" },
            { "Austria", "AT" },
            { "Aruba", "AW" },
            { "Azerbaijan", "AZ" },
            { "Bosnia and Herzegovina", "BA" },
            { "Barbados", "BB" },
            { "Bangladesh", "BD" },
            { "Belgium", "BE" },
            { "Burkina Faso", "BF" },
            { "Bulgaria", "BG" },
            { "Bahrain", "BH" },
            { "Burundi", "BI" },
            { "Benin", "BJ" },
            { "Bermuda", "BM" },
            { "Brunei Darussalam", "BN" },
            { "Bolivia", "BO" },
            { "Brazil", "BR" },
            { "Bahamas", "BS" },
            { "Bhutan", "BT" },
            { "Bouvet Island", "BV" },
            { "Botswana", "BW" },
            { "Belarus", "BY" },
            { "Belize", "BZ" },
            { "Canada", "CA" },
            { "Cocos (Keeling) Islands", "CC" },
            { "Congo, the Democratic Republic of the", "CD" },
            { "Central African Republic", "CF" },
            { "Congo", "CG" },
            { "Switzerland", "CH" },
            { "Cote D'Ivoire", "CI" },
            { "Cook Islands", "CK" },
            { "Chile", "CL" },
            { "Cameroon", "CM" },
            { "China", "CN" },
            { "Colombia", "CO" },
            { "Costa Rica", "CR" },
            { "Serbia and Montenegro", "CS" },
            { "Cuba", "CU" },
            { "Cape Verde", "CV" },
            { "Christmas Island", "CX" },
            { "Cyprus", "CY" },
            { "Czech Republic", "CZ" },
            { "Germany", "DE" },
            { "Djibouti", "DJ" },
            { "Denmark", "DK" },
            { "Dominica", "DM" },
            { "Dominican Republic", "DO" },
            { "Algeria", "DZ" },
            { "Ecuador", "EC" },
            { "Estonia", "EE" },
            { "Egypt", "EG" },
            { "Western Sahara", "EH" },
            { "Eritrea", "ER" },
            { "Spain", "ES" },
            { "Ethiopia", "ET" },
            { "Finland", "FI" },
            { "Fiji", "FJ" },
            { "Falkland Islands (Malvinas)", "FK" },
            { "Micronesia, Federated States of", "FM" },
            { "Faroe Islands", "FO" },
            { "France", "FR" },
            { "Gabon", "GA" },
            { "Grenada", "GD" },
            { "Georgia", "GE" },
            { "French Guiana", "GF" },
            { "Ghana", "GH" },
            { "Gibraltar", "GI" },
            { "Greenland", "GL" },
            { "Gambia", "GM" },
            { "Guinea", "GN" },
            { "Guadeloupe", "GP" },
            { "Equatorial Guinea", "GQ" },
            { "Greece", "GR" },
            { "South Georgia and the South Sandwich Islands", "GS" },
            { "Guatemala", "GT" },
            { "Guam", "GU" },
            { "Guinea-Bissau", "GW" },
            { "Guyana", "GY" },
            { "Hong Kong", "HK" },
            { "Heard Island and McDonald Islands", "HM" },
            { "Honduras", "HN" },
            { "Croatia", "HR" },
            { "Haiti", "HT" },
            { "Hungary", "HU" },
            { "Indonesia", "ID" },
            { "Ireland", "IE" },
            { "Israel", "IL" },
            { "India", "IN" },
            { "British Indian Ocean Territory", "IO" },
            { "Iraq", "IQ" },
            { "Iran, Islamic Republic of", "IR" },
            { "Iceland", "IS" },
            { "Italy", "IT" },
            { "Jersey", "JE" },
            { "Jamaica", "JM" },
            { "Jordan", "JO" },
            { "Japan", "JP" },
            { "Kenya", "KE" },
            { "Kyrgyzstan", "KG" },
            { "Cambodia", "KH" },
            { "Kiribati", "KI" },
            { "Comoros", "KM" },
            { "Saint Kitts and Nevis", "KN" },
            { "Korea, Democratic People's Republic of", "KP" },
            { "Korea, Republic of", "KR" },
            { "Kuwait", "KW" },
            { "Cayman Islands", "KY" },
            { "Kazakhstan", "KZ" },
            { "Lao People's Democratic Republic", "LA" },
            { "Lebanon", "LB" },
            { "Saint Lucia", "LC" },
            { "Liechtenstein", "LI" },
            { "Sri Lanka", "LK" },
            { "Liberia", "LR" },
            { "Lesotho", "LS" },
            { "Lithuania", "LT" },
            { "Luxembourg", "LU" },
            { "Latvia", "LV" },
            { "Libyan Arab Jamahiriya", "LY" },
            { "Morocco", "MA" },
            { "Saint Martin", "MF" },
            { "Monaco", "MC" },
            { "Moldova, Republic of", "MD" },
            { "Madagascar", "MG" },
            { "Marshall Islands", "MH" },
            { "Macedonia, the Former Yugoslav Republic of", "MK" },
            { "Mali", "ML" },
            { "Myanmar", "MM" },
            { "Mongolia", "MN" },
            { "Macao", "MO" },
            { "Northern Mariana Islands", "MP" },
            { "Martinique", "MQ" },
            { "Mauritania", "MR" },
            { "Montserrat", "MS" },
            { "Malta", "MT" },
            { "Mauritius", "MU" },
            { "Maldives", "MV" },
            { "Malawi", "MW" },
            { "Mexico", "MX" },
            { "Malaysia", "MY" },
            { "Mozambique", "MZ" },
            { "Namibia", "NA" },
            { "New Caledonia", "NC" },
            { "Niger", "NE" },
            { "Norfolk Island", "NF" },
            { "Nigeria", "NG" },
            { "Nicaragua", "NI" },
            { "Netherlands", "NL" },
            { "Norway", "NO" },
            { "Nepal", "NP" },
            { "Nauru", "NR" },
            { "Niue", "NU" },
            { "New Zealand", "NZ" },
            { "Oman", "OM" },
            { "Panama", "PA" },
            { "Peru", "PE" },
            { "French Polynesia", "PF" },
            { "Papua New Guinea", "PG" },
            { "Philippines", "PH" },
            { "Pakistan", "PK" },
            { "Poland", "PL" },
            { "Portugal", "PT" },
            { "Qatar", "QA" },
            { "Romania", "RO" },
            { "Russian Federation", "RU" },
            { "Rwanda", "RW" },
            { "Saudi Arabia", "SA" },
            { "Sweden", "SE" },
            { "Singapore", "SG" },
            { "Slovenia", "SI" },
            { "Slovakia", "SK" },
            { "Sierra Leone", "SL" },
            { "San Marino", "SM" },
            { "Senegal", "SN" },
            { "Somalia", "SO" },
            { "Suriname", "SR" },
            { "Sao Tome and Principe", "ST" },
            { "El Salvador", "SV" },
            { "Syrian Arab Republic", "SY" },
            { "Eswatini", "SZ" },
            { "Chad", "TD" },
            { "Togo", "TG" },
            { "Thailand", "TH" },
            { "Tajikistan", "TJ" },
            { "Timor-Leste", "TL" },
            { "Turkmenistan", "TM" },
            { "Tunisia", "TN" },
            { "Tonga", "TO" },
            { "Turkey", "TR" },
            { "Trinidad and Tobago", "TT" },
            { "Tuvalu", "TV" },
            { "Taiwan, Province of China", "TW" },
            { "Tanzania, United Republic of", "TZ" },
            { "Ukraine", "UA" },
            { "Uganda", "UG" },
            { "United Kingdom", "GB" },
            { "Uruguay", "UY" },
            { "Uzbekistan", "UZ" },
            { "Venezuela", "VE" },
            { "Viet Nam", "VN" },
            { "Zambia", "ZM" },
            { "Zimbabwe", "ZW" }
        };
    }
}
